version: '3.7'

services:
  eventstore.db:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.67-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
